descriptor-schema-version: "2.7"
info:
  name: ghcr.io/rikeardi/iperf3
  description: buildkit.dockerfile.v0
  version: alpine-3.20.3_iperf3-3.17.1-r0
author:
  name: Rikeardi
  link: https://github.com/rikeardi
app:
  cpuarch: x86_64
  env:
    APP_DIR: /app
    APP_USER: app
    CONF_DIR: /app/conf
    DATA_DIR: /app/data
    IPERF_VERSION: 3.17.1-r0
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  resources:
    cpu: "400"
    memory: "128"
    network:
    - interface-name: eth0
      ports:
        tcp:
        - "5201"
        udp:
        - "5201"
    profile: custom
  startup:
    args:
    - -s
    rootfs: rootfs.tar
    target:
    - iperf3
    user: app
    workdir: /app
  type: docker