name: Tar file release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - id: vars
        run: |
          echo ::set-output name=alpine_version::$(grep '^FROM ghcr.io/ironpeakservices/iron-alpine/iron-alpine' Dockerfile | cut -d ' ' -f 2 | cut -d ':' -f 2)
          echo ::set-output name=iperf_version::$(grep '^ENV IPERF_VERSION' Dockerfile | cut -d ' ' -f 2 | cut -d '=' -f 2)

      - name: Download ioxclient and run it
        run: |
          wget -c https://pubhub.devnetcloud.com/media/iox/docs/artifacts/ioxclient/ioxclient-v1.17.0.0/ioxclient_1.17.0.0_linux_amd64.tar.gz -O - | tar -xz
          wget https://raw.githubusercontent.com/${{ env.IMAGE_NAME }}/refs/heads/master/package/package.yaml
          wget https://raw.githubusercontent.com/${{ env.IMAGE_NAME }}/refs/heads/master/.ioxclientcfg.yaml -O /home/runner/.ioxclientcfg.yaml
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          ioxclient_1.17.0.0_linux_amd64/ioxclient docker package --skip-schema-validation ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} . -n iperf3.tar

#      - name: Build an image from Dockerfile
#        run: |
#          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
    
#      - name: Create TAR file
#        run: |
#          docker save ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} -o iperf3.tar
    
      - name: Publish the TAR file
        run: |
          gh release delete alpine-${{ steps.vars.outputs.alpine_version }}_iperf3-${{ steps.vars.outputs.iperf_version }} --yes
          gh release create alpine-${{ steps.vars.outputs.alpine_version }}_iperf3-${{ steps.vars.outputs.iperf_version }} iperf3.tar
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash