name: Tar file release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - id: vars
        run: |
          echo ::set-output name=alpine_version::$(grep '^FROM ghcr.io/ironpeakservices/iron-alpine/iron-alpine' Dockerfile | cut -d ' ' -f 2 | cut -d ':' -f 2)
          echo ::set-output name=iperf_version::$(grep '^RUN apk add --no-cache iperf3' Dockerfile | cut -d ' ' -f 2 | cut -d '=' -f 2)

      - name: Build an image from Dockerfile
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
    
      - name: Create TAR file
        run: |
          docker save ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} -o iperf3.tar
    
      - name: Publish the TAR file
        run: |
          gh release create alpine-${{ steps.vars.outputs.alpine_version }}_iperf3-${{ steps.vars.outputs.iperf_version }} iperf3.tar
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash